App:
  description: 一斉架電
  type: object
  properties:
    id:
      description: 一斉架電ID
      type: string
      pattern: ^app[2-7A-Z]{16}$
      example: appYTW5CXCOHCNOVU3I
    name:
      description: |
        架電名
      type: string
      nullable: true
      minLength: 1
      maxLength: 191
      example: 事案No111-1
    description:
      description: 説明
      type: string
      nullable: true
      example: 事案No111の架電
    path:
      description: アプリ固有のpath
      type: string
      nullable: true
      example: txp-example.com
    icon:
      description: iconのfileId
      type: string
      nullable: true
      example: filYTW5CXCOHCNOVU3I
    createdAt:
      description: 作成日時
      type: string
      format: date-time
      example: 2021-01-23T01:23:45.678Z
    updatedAt:
      description: 更新日時（最初は作成日時）
      type: string
      format: date-time
      example: 2021-01-23T01:23:45.678Z
  required:
    - id
    - name
    - path
    - createdAt
    - updatedAt

AppExample1:
  value:
    id: appYTW5CXCOHCNOVU3I
    name: NSEYE
    description: 動画共有アプリ
    path: txp-example.com/#nseye 
    createdAt: "2021-01-23T01:23:45.678Z"
    updatedAt: "2021-01-23T01:23:45.678Z"

Apps:
  type: array
  items:
    $ref: "#/App"

AppsResponse:
  description: アプリ一覧
  type: object
  properties:
    pager:
      $ref: "./Pager.yml#/Pager"
    data:
      $ref: "./App.yml#/Apps"
  required:
    - pager
    - data

AppsResponseExample:
  value:
    data:
      - id: appYTW5CXCOHCNOVU3I
        name: NSEYE
        description: 動画共有アプリ
        path: txp-example.com/#nseye 
        createdAt: "2021-01-23T01:23:45.678Z"
        updatedAt: "2021-01-23T01:23:45.678Z"
      - id: appYTW5CXCOHCNOVU3I
        name: NSECG
        description: 12ECGアプリ
        path: txp-example.com/#ecg 
        createdAt: "2021-01-23T01:23:45.678Z"
        updatedAt: "2021-01-23T01:23:45.678Z"